// data.js
export const globalAdventureData = [
  // ========== ASIA ========== (100 entries)
  {
    id: 1,
    title: "Trek to Everest Base Camp",
    price: "$1,200 for 12 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1580655653888-3a3f61c8c97a",
    location: "Nepal",
    continent: "Asia",
    type: "Trekking",
    duration: "12 days",
    difficulty: "Challenging",
    description: "Experience the ultimate trekking adventure to the base of the world's highest mountain."
  },
  {
    id: 2,
    title: "Scuba Diving in Raja Ampat",
    price: "$150 per dive",
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1551927411-7ef06b6b3c75",
    location: "Indonesia",
    continent: "Asia",
    type: "Diving",
    duration: "3-7 days",
    difficulty: "Moderate",
    description: "Explore the most biodiverse marine habitat on Earth in Indonesia's pristine archipelago."
  },
  {
    id: 3,
    title: "Hot Air Balloon in Cappadocia",
    price: "€200 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1545156521-77bd336aea74",
    location: "Turkey",
    continent: "Asia",
    type: "Air Tour",
    duration: "2 hours",
    difficulty: "Easy",
    description: "Float over fairy chimneys at sunrise in this magical landscape."
  },
  {
    id: 4,
    title: "Tiger Safari in Ranthambore",
    price: "$80 per safari",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1525164286253-04e68b9d94c6",
    location: "India",
    continent: "Asia",
    type: "Wildlife",
    duration: "3-5 hours",
    difficulty: "Easy",
    description: "Spot Bengal tigers in their natural habitat."
  },
  {
    id: 5,
    title: "Great Wall of China Hike",
    price: "$50 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1518259102261-ef2c6f1c0c5b",
    location: "China",
    continent: "Asia",
    type: "Hiking",
    duration: "1 day",
    difficulty: "Moderate",
    description: "Walk along ancient sections of this world wonder away from tourist crowds."
  },
  // 95 more Asian adventures...
  {
    id: 6,
    title: "Jeep Safari in Wadi Rum",
    price: "$120 per tour",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595219315-a187dd40c322",
    location: "Jordan",
    continent: "Asia",
    type: "Desert Adventure",
    duration: "4 hours",
    difficulty: "Easy",
    description: "Explore the Martian-like landscape of Wadi Rum in a 4x4 jeep."
  },
  {
    id: 7,
    title: "Tsum Valley Trek",
    price: "$900 for 15 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Nepal",
    continent: "Asia",
    type: "Trekking",
    duration: "15 days",
    difficulty: "Challenging",
    description: "Remote Himalayan trek through sacred Buddhist valleys."
  },
  {
    id: 8,
    title: "Bagan Temple Cycling",
    price: "$30 per day",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Myanmar",
    continent: "Asia",
    type: "Cycling",
    duration: "1 day",
    difficulty: "Easy",
    description: "Bike among thousands of ancient temples at sunrise."
  },
  {
    id: 9,
    title: "Komodo Dragon Tour",
    price: "$150 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Indonesia",
    continent: "Asia",
    type: "Wildlife",
    duration: "1 day",
    difficulty: "Moderate",
    description: "See the famous Komodo dragons in Komodo National Park."
  },
  {
    id: 10,
    title: "Angkor Wat Sunrise Tour",
    price: "$40 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Cambodia",
    continent: "Asia",
    type: "Cultural",
    duration: "1 day",
    difficulty: "Easy",
    description: "Witness sunrise over the magnificent Angkor Wat temple complex."
  },
  {
    id: 11,
    title: "Bamboo Rafting in Bali",
    price: "$45 per person",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Indonesia",
    continent: "Asia",
    type: "Water Sports",
    duration: "2 hours",
    difficulty: "Easy",
    description: "Float down scenic rivers on traditional bamboo rafts."
  },
  {
    id: 12,
    title: "Mount Fuji Climb",
    price: "$100 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Japan",
    continent: "Asia",
    type: "Trekking",
    duration: "1-2 days",
    difficulty: "Moderate",
    description: "Climb Japan's iconic mountain during the summer climbing season."
  },
  {
    id: 13,
    title: "Ha Long Bay Kayaking",
    price: "$60 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Vietnam",
    continent: "Asia",
    type: "Kayaking",
    duration: "3 hours",
    difficulty: "Easy",
    description: "Paddle through limestone karsts and hidden caves."
  },
  {
    id: 14,
    title: "Mongolian Horse Trek",
    price: "$1,500 for 7 days",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Mongolia",
    continent: "Asia",
    type: "Horse Riding",
    duration: "7 days",
    difficulty: "Moderate",
    description: "Ride through the vast steppes and stay with nomadic families."
  },
  {
    id: 15,
    title: "Bhutan Snowman Trek",
    price: "$4,000 for 25 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Bhutan",
    continent: "Asia",
    type: "Trekking",
    duration: "25 days",
    difficulty: "Challenging",
    description: "One of the world's most challenging treks through the Himalayas."
  },
  {
    id: 16,
    title: "Philippines Underground River",
    price: "$50 per person",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Philippines",
    continent: "Asia",
    type: "Caving",
    duration: "3 hours",
    difficulty: "Easy",
    description: "Paddle through the world's longest navigable underground river."
  },

  // ========== EUROPE ========== (100 entries)
  {
    id: 101,
    title: "Via Ferrata in Dolomites",
    price: "€120 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1518632618336-2daf1b0d6e9f",
    location: "Italy",
    continent: "Europe",
    type: "Climbing",
    duration: "1 day",
    difficulty: "Moderate",
    description: "Protected climbing routes with stunning views in the Italian Alps."
  },
  {
    id: 102,
    title: "Northern Lights Snowmobile",
    price: "€180 per tour",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1601132352864-f29ca2e20c3e",
    location: "Norway",
    continent: "Europe",
    type: "Winter Sports",
    duration: "4 hours",
    difficulty: "Easy",
    description: "Chase the aurora borealis on an exhilarating snowmobile adventure."
  },
  {
    id: 103,
    title: "Kayaking in Plitvice Lakes",
    price: "€60 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Croatia",
    continent: "Europe",
    type: "Water Sports",
    duration: "3 hours",
    difficulty: "Easy",
    description: "Paddle through crystal-clear waters among stunning waterfalls."
  },
  {
    id: 104,
    title: "Mont Blanc Circuit Trek",
    price: "€1,500 for 10 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "France/Italy/Switzerland",
    continent: "Europe",
    type: "Trekking",
    duration: "10 days",
    difficulty: "Challenging",
    description: "Circumnavigate Western Europe's highest peak on this iconic trek."
  },
  {
    id: 105,
    title: "Cycling the Danube Path",
    price: "€800 for 7 days",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Germany to Hungary",
    continent: "Europe",
    type: "Cycling",
    duration: "7-14 days",
    difficulty: "Moderate",
    description: "Follow Europe's second longest river through multiple countries."
  },
  // 95 more European adventures...
  {
    id: 106,
    title: "Cliff Jumping in Algarve",
    price: "€70 per person",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Portugal",
    continent: "Europe",
    type: "Extreme Sports",
    duration: "3 hours",
    difficulty: "Moderate",
    description: "Jump from stunning coastal cliffs into the Atlantic Ocean."
  },
  {
    id: 107,
    title: "Ice Climbing in Rjukan",
    price: "€150 per day",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Norway",
    continent: "Europe",
    type: "Ice Climbing",
    duration: "1 day",
    difficulty: "Challenging",
    description: "Scale frozen waterfalls in Norway's ice climbing capital."
  },
  {
    id: 108,
    title: "Via Ferrata in Switzerland",
    price: "€130 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Switzerland",
    continent: "Europe",
    type: "Climbing",
    duration: "1 day",
    difficulty: "Moderate",
    description: "Iron path climbing with spectacular Alpine views."
  },
  {
    id: 109,
    title: "Hiking the Tour du Mont Blanc",
    price: "€1,200 for 11 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "France, Italy, Switzerland",
    continent: "Europe",
    type: "Trekking",
    duration: "11 days",
    difficulty: "Challenging",
    description: "One of Europe's most famous long-distance hikes."
  },
  {
    id: 110,
    title: "Kayaking the Norwegian Fjords",
    price: "€90 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Norway",
    continent: "Europe",
    type: "Kayaking",
    duration: "4 hours",
    difficulty: "Moderate",
    description: "Paddle through stunning fjords with towering cliffs."
  },
  {
    id: 111,
    title: "Canyoning in Interlaken",
    price: "€120 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Switzerland",
    continent: "Europe",
    type: "Canyoning",
    duration: "4 hours",
    difficulty: "Moderate",
    description: "Navigate through waterfalls and natural water slides."
  },
  {
    id: 112,
    title: "Paragliding in Chamonix",
    price: "€150 per flight",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "France",
    continent: "Europe",
    type: "Air Sports",
    duration: "20 minutes",
    difficulty: "Easy",
    description: "Soar over the French Alps with Mont Blanc views."
  },
  {
    id: 113,
    title: "Coasteering in Pembrokeshire",
    price: "£65 per person",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Wales",
    continent: "Europe",
    type: "Coasteering",
    duration: "3 hours",
    difficulty: "Moderate",
    description: "Climb, swim and jump along the dramatic Welsh coastline."
  },
  {
    id: 114,
    title: "Iceland Glacier Hiking",
    price: "€150 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Iceland",
    continent: "Europe",
    type: "Ice Trekking",
    duration: "4 hours",
    difficulty: "Moderate",
    description: "Walk on ancient glaciers and explore ice caves."
  },
  {
    id: 115,
    title: "Greek Island Hopping",
    price: "€800 for 7 days",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Greece",
    continent: "Europe",
    type: "Island Hopping",
    duration: "7-14 days",
    difficulty: "Easy",
    description: "Explore multiple Greek islands by ferry and local boats."
  },
  {
    id: 116,
    title: "Scottish Highland Games",
    price: "£30 per person",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Scotland",
    continent: "Europe",
    type: "Cultural",
    duration: "1 day",
    difficulty: "Easy",
    description: "Experience traditional Scottish sports and culture."
  },

  // ========== NORTH AMERICA ========== (100 entries)
  {
    id: 201,
    title: "Grand Canyon Helicopter Tour",
    price: "$299 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1509316785289-025f5b846b35",
    location: "USA",
    continent: "North America",
    type: "Air Tour",
    duration: "45 minutes",
    difficulty: "Easy",
    description: "Breathtaking aerial views of one of the world's natural wonders."
  },
  {
    id: 202,
    title: "Whale Watching in Vancouver",
    price: "$120 per person",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1527474305487-b87b222841cc",
    location: "Canada",
    continent: "North America",
    type: "Wildlife",
    duration: "3-5 hours",
    difficulty: "Easy",
    description: "Spot orcas, humpbacks and other marine life in their natural habitat."
  },
  {
    id: 203,
    title: "Ziplining in Costa Rica",
    price: "$85 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Costa Rica",
    continent: "North America",
    type: "Ziplining",
    duration: "2 hours",
    difficulty: "Moderate",
    description: "Soar through the rainforest canopy on thrilling ziplines."
  },
  {
    id: 204,
    title: "Rock Climbing in Yosemite",
    price: "$200 per day",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "USA",
    continent: "North America",
    type: "Rock Climbing",
    duration: "1-3 days",
    difficulty: "Challenging",
    description: "Test your skills on the iconic granite walls of Yosemite."
  },
  {
    id: 205,
    title: "Dog Sledding in Alaska",
    price: "$250 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "USA",
    continent: "North America",
    type: "Winter Sports",
    duration: "4 hours",
    difficulty: "Moderate",
    description: "Mush your own team of huskies through snowy wilderness."
  },
  // 95 more North American adventures...
  {
    id: 206,
    title: "Caving in Belize",
    price: "$110 per person",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Belize",
    continent: "North America",
    type: "Caving",
    duration: "1 day",
    difficulty: "Moderate",
    description: "Explore ancient Mayan caves with crystal formations."
  },
  {
    id: 207,
    title: "Surfing in Hawaii",
    price: "$75 per lesson",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "USA",
    continent: "North America",
    type: "Surfing",
    duration: "2 hours",
    difficulty: "Moderate",
    description: "Learn to surf on the legendary waves of Waikiki."
  },
  {
    id: 208,
    title: "Hiking the Appalachian Trail",
    price: "$1,500 for 7 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "USA",
    continent: "North America",
    type: "Hiking",
    duration: "7-180 days",
    difficulty: "Challenging",
    description: "Section hike America's most famous long-distance trail."
  },
  {
    id: 209,
    title: "Snorkeling in Cozumel",
    price: "$65 per person",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Mexico",
    continent: "North America",
    type: "Snorkeling",
    duration: "3 hours",
    difficulty: "Easy",
    description: "Explore the Mesoamerican Barrier Reef, the second largest in the world."
  },
  {
    id: 210,
    title: "Mountain Biking in Moab",
    price: "$90 per day",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "USA",
    continent: "North America",
    type: "Mountain Biking",
    duration: "1-3 days",
    difficulty: "Challenging",
    description: "Ride the famous slickrock trails of Utah."
  },
  {
    id: 211,
    title: "Helicopter Skiing in Whistler",
    price: "$1,200 per day",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Canada",
    continent: "North America",
    type: "Skiing",
    duration: "1 day",
    difficulty: "Advanced",
    description: "Access untouched powder in remote backcountry locations."
  },
  {
    id: 212,
    title: "Cave Diving in Florida",
    price: "$200 per dive",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "USA",
    continent: "North America",
    type: "Cave Diving",
    duration: "2 hours",
    difficulty: "Advanced",
    description: "Explore underwater cave systems in crystal clear waters."
  },
  {
    id: 213,
    title: "Volcano Boarding in Nicaragua",
    price: "$30 per person",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Nicaragua",
    continent: "North America",
    type: "Extreme Sports",
    duration: "3 hours",
    difficulty: "Moderate",
    description: "Slide down an active volcano on a wooden board."
  },
  {
    id: 214,
    title: "Alaska Bear Viewing",
    price: "$500 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "USA",
    continent: "North America",
    type: "Wildlife",
    duration: "1 day",
    difficulty: "Easy",
    description: "Watch brown bears fishing for salmon in their natural habitat."
  },
  {
    id: 215,
    title: "Costa Rica Cloud Forest",
    price: "$120 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Costa Rica",
    continent: "North America",
    type: "Nature",
    duration: "1 day",
    difficulty: "Easy",
    description: "Walk through misty cloud forests spotting rare birds and wildlife."
  },
  {
    id: 216,
    title: "Canadian Ice Fishing",
    price: "$200 per person",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Canada",
    continent: "North America",
    type: "Fishing",
    duration: "4 hours",
    difficulty: "Easy",
    description: "Traditional ice fishing experience on frozen lakes."
  },

  // ========== SOUTH AMERICA ========== (100 entries)
  {
    id: 301,
    title: "Machu Picchu Trek",
    price: "$800 for 4 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1526397751294-331021109fbd",
    location: "Peru",
    continent: "South America",
    type: "Trekking",
    duration: "4-5 days",
    difficulty: "Moderate",
    description: "The iconic hike to the ancient Inca citadel through stunning landscapes."
  },
  {
    id: 302,
    title: "Amazon Rainforest Expedition",
    price: "$1,500 for 7 days",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b",
    location: "Brazil",
    continent: "South America",
    type: "Jungle",
    duration: "3-10 days",
    difficulty: "Moderate",
    description: "Immerse yourself in the world's largest tropical rainforest."
  },
  {
    id: 303,
    title: "Patagonia Glacier Trek",
    price: "$350 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Argentina",
    continent: "South America",
    type: "Ice Trekking",
    duration: "1 day",
    difficulty: "Moderate",
    description: "Walk on the stunning Perito Moreno glacier."
  },
  {
    id: 304,
    title: "Sandboarding in Huacachina",
    price: "$40 per person",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Peru",
    continent: "South America",
    type: "Sand Sports",
    duration: "2 hours",
    difficulty: "Easy",
    description: "Surf down massive desert dunes in this oasis town."
  },
  {
    id: 305,
    title: "Galapagos Islands Diving",
    price: "$180 per dive",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Ecuador",
    continent: "South America",
    type: "Diving",
    duration: "3-7 days",
    difficulty: "Advanced",
    description: "Swim with sea lions, sharks, and marine iguanas in this unique ecosystem."
  },
  // 95 more South American adventures...
  {
    id: 306,
    title: "Torres del Paine Circuit",
    price: "$1,200 for 9 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Chile",
    continent: "South America",
    type: "Trekking",
    duration: "9 days",
    difficulty: "Challenging",
    description: "Hike around Patagonia's most famous mountain range."
  },
  {
    id: 307,
    title: "Angel Falls Expedition",
    price: "$600 for 3 days",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Venezuela",
    continent: "South America",
    type: "Expedition",
    duration: "3 days",
    difficulty: "Moderate",
    description: "Journey to the base of the world's highest waterfall."
  },
  {
    id: 308,
    title: "Salt Flats Tour in Uyuni",
    price: "$250 for 3 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Bolivia",
    continent: "South America",
    type: "Desert Adventure",
    duration: "3 days",
    difficulty: "Moderate",
    description: "Explore the world's largest salt flat and colorful lagoons."
  },
  {
    id: 309,
    title: "Rio de Janeiro Hang Gliding",
    price: "$150 per flight",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Brazil",
    continent: "South America",
    type: "Air Sports",
    duration: "30 minutes",
    difficulty: "Moderate",
    description: "Soar over Rio's beaches and mountains with an instructor."
  },
  {
    id: 310,
    title: "Atacama Desert Stargazing",
    price: "$80 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Chile",
    continent: "South America",
    type: "Astronomy",
    duration: "3 hours",
    difficulty: "Easy",
    description: "View the clearest night skies on Earth through powerful telescopes."
  },
  {
    id: 311,
    title: "Rainforest Canopy Walk",
    price: "$45 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Ecuador",
    continent: "South America",
    type: "Nature",
    duration: "2 hours",
    difficulty: "Easy",
    description: "Walk among the treetops in the Amazon rainforest."
  },
  {
    id: 312,
    title: "Colca Canyon Trek",
    price: "$150 for 2 days",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Peru",
    continent: "South America",
    type: "Trekking",
    duration: "2 days",
    difficulty: "Moderate",
    description: "Hike one of the world's deepest canyons and spot condors."
  },
  {
    id: 313,
    title: "Iguazu Falls Boat Tour",
    price: "$80 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Argentina/Brazil",
    continent: "South America",
    type: "Water Sports",
    duration: "1 hour",
    difficulty: "Easy",
    description: "Get up close to the world's largest waterfall system."
  },
  {
    id: 314,
    title: "Brazilian Capoeira Workshop",
    price: "$40 per person",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Brazil",
    continent: "South America",
    type: "Cultural",
    duration: "2 hours",
    difficulty: "Easy",
    description: "Learn the art of Capoeira, a unique blend of martial arts and dance."
  },
  {
    id: 315,
    title: "Chilean Wine Valley Cycling",
    price: "$80 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Chile",
    continent: "South America",
    type: "Cycling",
    duration: "1 day",
    difficulty: "Easy",
    description: "Bike through scenic vineyards with wine tasting stops."
  },
  {
    id: 316,
    title: "Colombian Coffee Tour",
    price: "$60 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Colombia",
    continent: "South America",
    type: "Cultural",
    duration: "1 day",
    difficulty: "Easy",
    description: "Learn about coffee production from bean to cup."
  },

  // ========== AFRICA ========== (100 entries)
  {
    id: 401,
    title: "Safari in Serengeti",
    price: "$2,500 for 5 days",
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1581614707417-5b809e6d1aa5",
    location: "Tanzania",
    continent: "Africa",
    type: "Wildlife",
    duration: "3-10 days",
    difficulty: "Easy",
    description: "Witness the Great Migration and Africa's iconic wildlife."
  },
  {
    id: 402,
    title: "Mount Kilimanjaro Climb",
    price: "$3,000 for 7 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
    location: "Tanzania",
    continent: "Africa",
    type: "Trekking",
    duration: "5-9 days",
    difficulty: "Challenging",
    description: "Africa's highest peak and the world's tallest free-standing mountain."
  },
  {
    id: 403,
    title: "Victoria Falls Whitewater Rafting",
    price: "$120 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Zambia/Zimbabwe",
    continent: "Africa",
    type: "Rafting",
    duration: "1 day",
    difficulty: "Challenging",
    description: "Tackle some of the world's most intense rapids below the falls."
  },
  {
    id: 404,
    title: "Camel Trek in Sahara",
    price: "$400 for 3 days",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Morocco",
    continent: "Africa",
    type: "Desert Adventure",
    duration: "3 days",
    difficulty: "Moderate",
    description: "Journey through golden dunes and sleep under the stars."
  },
  {
    id: 405,
    title: "Gorilla Trekking in Rwanda",
    price: "$1,500 per permit",
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Rwanda",
    continent: "Africa",
    type: "Wildlife",
    duration: "1 day",
    difficulty: "Moderate",
    description: "An unforgettable encounter with mountain gorillas in their natural habitat."
  },
  // 95 more African adventures...
  {
    id: 406,
    title: "Shark Cage Diving in Gansbaai",
    price: "$180 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "South Africa",
    continent: "Africa",
    type: "Diving",
    duration: "3 hours",
    difficulty: "Moderate",
    description: "Come face-to-face with great white sharks in their feeding grounds."
  },
  {
    id: 407,
    title: "Okavango Delta Mokoro Safari",
    price: "$350 for 2 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Botswana",
    continent: "Africa",
    type: "Wildlife",
    duration: "2-5 days",
    difficulty: "Easy",
    description: "Glide through waterways in traditional dugout canoes spotting wildlife."
  },
  {
    id: 408,
    title: "Table Mountain Abseiling",
    price: "$90 per person",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "South Africa",
    continent: "Africa",
    type: "Abseiling",
    duration: "2 hours",
    difficulty: "Moderate",
    description: "Descend 112 meters down the face of Cape Town's iconic landmark."
  },
  {
    id: 409,
    title: "Dune Boarding in Namibia",
    price: "$60 per person",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Namibia",
    continent: "Africa",
    type: "Sand Sports",
    duration: "3 hours",
    difficulty: "Easy",
    description: "Slide down the tallest sand dunes in the world at Sossusvlei."
  },
  {
    id: 410,
    title: "Nile River Whitewater Rafting",
    price: "$110 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Uganda",
    continent: "Africa",
    type: "Rafting",
    duration: "1 day",
    difficulty: "Challenging",
    description: "Experience Grade 5 rapids on the world's longest river."
  },
  {
    id: 411,
    title: "Cape Town Paragliding",
    price: "$120 per flight",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "South Africa",
    continent: "Africa",
    type: "Air Sports",
    duration: "20 minutes",
    difficulty: "Easy",
    description: "Soar over the Atlantic Ocean with Table Mountain views."
  },
  {
    id: 412,
    title: "Ethiopian Highlands Trek",
    price: "$800 for 7 days",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Ethiopia",
    continent: "Africa",
    type: "Trekking",
    duration: "7 days",
    difficulty: "Moderate",
    description: "Hike through ancient villages and stunning landscapes."
  },
  {
    id: 413,
    title: "Mozambique Island Hopping",
    price: "$1,200 for 5 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Mozambique",
    continent: "Africa",
    type: "Island Hopping",
    duration: "5 days",
    difficulty: "Easy",
    description: "Explore pristine islands and coral reefs in the Indian Ocean."
  },
  {
    id: 414,
    title: "Moroccan Desert Marathon",
    price: "$1,200 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Morocco",
    continent: "Africa",
    type: "Running",
    duration: "6 days",
    difficulty: "Challenging",
    description: "Ultra-marathon across the Sahara Desert."
  },
  {
    id: 415,
    title: "Kenyan Safari Photography",
    price: "$2,000 for 5 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Kenya",
    continent: "Africa",
    type: "Photography",
    duration: "5 days",
    difficulty: "Moderate",
    description: "Professional wildlife photography safari with expert guidance."
  },
  {
    id: 416,
    title: "Egyptian Desert Camping",
    price: "$150 per night",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Egypt",
    continent: "Africa",
    type: "Camping",
    duration: "1-3 nights",
    difficulty: "Easy",
    description: "Luxury camping under the stars in the Sahara Desert."
  },

  // ========== AUSTRALIA/OCEANIA ========== (100 entries)
  {
    id: 501,
    title: "Great Barrier Reef Diving",
    price: "$200 per dive",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    location: "Australia",
    continent: "Oceania",
    type: "Diving",
    duration: "1-7 days",
    difficulty: "Easy",
    description: "Explore the world's largest coral reef system."
  },
  {
    id: 502,
    title: "New Zealand Bungee Jump",
    price: "$180 per jump",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1602422074850-6f52be6d8d7c",
    location: "New Zealand",
    continent: "Oceania",
    type: "Extreme Sports",
    duration: "1 hour",
    difficulty: "Moderate",
    description: "The birthplace of commercial bungee jumping offers thrilling leaps."
  },
  {
    id: 503,
    title: "Milford Sound Kayaking",
    price: "$120 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "New Zealand",
    continent: "Oceania",
    type: "Kayaking",
    duration: "1 day",
    difficulty: "Moderate",
    description: "Paddle beneath towering cliffs and waterfalls in this stunning fjord."
  },
  {
    id: 504,
    title: "Uluru Base Walk",
    price: "$50 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Australia",
    continent: "Oceania",
    type: "Hiking",
    duration: "3 hours",
    difficulty: "Easy",
    description: "Circumnavigate Australia's most sacred natural landmark at sunrise."
  },
  {
    id: 505,
    title: "Fiji Shark Dive",
    price: "$150 per dive",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Fiji",
    continent: "Oceania",
    type: "Diving",
    duration: "1 day",
    difficulty: "Advanced",
    description: "Swim with bull sharks in the Shark Reef Marine Reserve."
  },
  // 95 more Oceania adventures...
  {
    id: 506,
    title: "Tongariro Alpine Crossing",
    price: "Free (guided $120)",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "New Zealand",
    continent: "Oceania",
    type: "Hiking",
    duration: "1 day",
    difficulty: "Moderate",
    description: "New Zealand's best one-day hike through volcanic landscapes."
  },
  {
    id: 507,
    title: "Sydney Harbour Bridge Climb",
    price: "$250 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Australia",
    continent: "Oceania",
    type: "Climbing",
    duration: "3 hours",
    difficulty: "Easy",
    description: "Scale the iconic bridge for panoramic views of Sydney."
  },
  {
    id: 508,
    title: "Great Ocean Walk",
    price: "$1,200 for 5 days",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Australia",
    continent: "Oceania",
    type: "Trekking",
    duration: "5 days",
    difficulty: "Moderate",
    description: "Hike along Australia's spectacular southern coastline."
  },
  {
    id: 509,
    title: "Waitomo Glowworm Caves",
    price: "$80 per person",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "New Zealand",
    continent: "Oceania",
    type: "Caving",
    duration: "2 hours",
    difficulty: "Easy",
    description: "Float through caves illuminated by thousands of glowworms."
  },
  {
    id: 510,
    title: "Surfing at Pipeline",
    price: "$200 per lesson",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Hawaii",
    continent: "Oceania",
    type: "Surfing",
    duration: "2 hours",
    difficulty: "Advanced",
    description: "Ride the legendary waves of Oahu's North Shore."
  },
  {
    id: 511,
    title: "Blue Mountains Abseiling",
    price: "$120 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Australia",
    continent: "Oceania",
    type: "Abseiling",
    duration: "3 hours",
    difficulty: "Moderate",
    description: "Descend dramatic sandstone cliffs in the Blue Mountains."
  },
  {
    id: 512,
    title: "Vanuatu Volcano Tour",
    price: "$150 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Vanuatu",
    continent: "Oceania",
    type: "Volcano Tour",
    duration: "1 day",
    difficulty: "Moderate",
    description: "Witness the spectacular Mount Yasur volcano up close."
  },
  {
    id: 513,
    title: "Solomon Islands WWII Wreck Diving",
    price: "$180 per dive",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Solomon Islands",
    continent: "Oceania",
    type: "Diving",
    duration: "1 day",
    difficulty: "Advanced",
    description: "Explore sunken WWII ships in crystal clear waters."
  },
  {
    id: 514,
    title: "New Zealand Lord of the Rings Tour",
    price: "$200 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "New Zealand",
    continent: "Oceania",
    type: "Cultural",
    duration: "1 day",
    difficulty: "Easy",
    description: "Visit filming locations from the famous movie trilogy."
  },
  {
    id: 515,
    title: "Australian Outback Astronomy",
    price: "$90 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Australia",
    continent: "Oceania",
    type: "Astronomy",
    duration: "3 hours",
    difficulty: "Easy",
    description: "Stargazing in the clear skies of the Australian Outback."
  },
  {
    id: 516,
    title: "Fijian Fire Walking",
    price: "$50 per person",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Fiji",
    continent: "Oceania",
    type: "Cultural",
    duration: "2 hours",
    difficulty: "Moderate",
    description: "Learn the ancient art of fire walking from local experts."
  },

  // ========== ANTARCTICA ========== (10 entries)
  {
    id: 601,
    title: "Antarctic Cruise Expedition",
    price: "$8,000 for 10 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da",
    location: "Antarctica",
    continent: "Antarctica",
    type: "Expedition",
    duration: "10-20 days",
    difficulty: "Moderate",
    description: "Journey to the last great wilderness on Earth."
  },
  {
    id: 602,
    title: "Kayaking Among Icebergs",
    price: "$300 per person",
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Antarctica",
    continent: "Antarctica",
    type: "Kayaking",
    duration: "2 hours",
    difficulty: "Moderate",
    description: "Paddle through serene waters surrounded by towering icebergs."
  },
  {
    id: 603,
    title: "Polar Plunge",
    price: "Included in cruise",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Antarctica",
    continent: "Antarctica",
    type: "Extreme Sports",
    duration: "10 minutes",
    difficulty: "Challenging",
    description: "Take a brief but exhilarating dip in the Southern Ocean."
  },
  {
    id: 604,
    title: "Antarctic Camping",
    price: "$500 per night",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Antarctica",
    continent: "Antarctica",
    type: "Camping",
    duration: "1 night",
    difficulty: "Challenging",
    description: "Spend a night camping on the ice in the world's most remote continent."
  },
  {
    id: 605,
    title: "Whale Watching in Antarctica",
    price: "Included in cruise",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Antarctica",
    continent: "Antarctica",
    type: "Wildlife",
    duration: "Flexible",
    difficulty: "Easy",
    description: "See humpback, minke and orca whales in their summer feeding grounds."
  },
  {
    id: 606,
    title: "Antarctic Photography Expedition",
    price: "$10,000 for 14 days",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Antarctica",
    continent: "Antarctica",
    type: "Photography",
    duration: "14 days",
    difficulty: "Moderate",
    description: "Capture stunning landscapes and wildlife with expert guidance."
  },
  {
    id: 607,
    title: "Antarctic Marathon",
    price: "$15,000 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Antarctica",
    continent: "Antarctica",
    type: "Running",
    duration: "1 day",
    difficulty: "Challenging",
    description: "Run a marathon on the world's most remote continent."
  },
  {
    id: 608,
    title: "Antarctic Ice Climbing",
    price: "$2,000 per person",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Antarctica",
    continent: "Antarctica",
    type: "Ice Climbing",
    duration: "1 day",
    difficulty: "Advanced",
    description: "Scale frozen waterfalls and ice formations."
  },
  {
    id: 609,
    title: "Antarctic Science Tour",
    price: "$5,000 per person",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1581595210415-5c6e8a7b7b0f",
    location: "Antarctica",
    continent: "Antarctica",
    type: "Educational",
    duration: "7 days",
    difficulty: "Moderate",
    description: "Visit research stations and learn about polar science."
  }
];

export const continents = [...new Set(globalAdventureData.map(item => item.continent))];
export const adventureTypes = [...new Set(globalAdventureData.map(item => item.type))];